### ISSUE TITLE
OSX: Error with BASH, CONTINUE function

### ISSUE THREAD

**Issue by dustinvanbuskirk** [codefresh-io/k8s-dind-config#7]
`.Codefresh/runtime/codefresh-k8s-configure.sh: line 166: ${CONTINUE,,}: bad substitution`

we ended up copying and hosting `codefresh-k8s-configure.sh` ourselves with the following replacement for line 166 which got it running

`CONTINUE=$(echo "$CONTINUE" | awk '{print tolower($0)}') # tolower`

**Comment by yaroslav-codefresh** [comment]
Bash 3 support issue is fixed
